### ISSUE TITLE
Error with <ConnectAccountOnboarding> in 1.3.1

### ISSUE THREAD

**Issue by nathanbullenmyob** [stripe/react-connect-js#25]
I have the following error when trying to display the ConnectAccountOnboarding in 1.3.1, 

```
react-connect.esm.js:89 Uncaught TypeError: Cannot read properties of null (reading 'create')
    at react-connect.esm.js:89:1
    at commitHookEffectListMount (react-dom.development.js:20042:1)
    at invokeLayoutEffectMountInDEV (react-dom.development.js:21702:1)
    at invokeEffectsInDev (react-dom.development.js:23630:1)
    at commitDoubleInvokeEffectsInDEV (react-dom.development.js:23611:1)
    at flushPassiveEffectsImpl (react-dom.development.js:23386:1)
    at flushPassiveEffects (react-dom.development.js:23324:1)
    at performSyncWorkOnRoot (react-dom.development.js:22541:1)
    at flushSyncCallbacks (react-dom.development.js:10573:1)
    at commitRootImpl (react-dom.development.js:23303:1)
```

```
The above error occurred in the <ConnectAccountOnboarding> component:
    at ConnectAccountOnboarding (http://localhost:3000/static/js/bundle.js:77277:34)
    at ConnectComponentsProvider (http://localhost:3000/static/js/bundle.js:77183:30)
    at div
    ..... flows onto our code
```

1.2.0 works fine :)

**Comment by jorgea-stripe** [comment]
Hey @nathanbullenmyob - we've since fixed this issue! Please update both the react-connect-js and connect-js npm packages. Let us know if this is working for you now.
